"use client"
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import store from "@/store/store";
import { Provider } from "react-redux";
import { useEffect } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function ServiceWorkerRegistration() {
  useEffect(() => {
    if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
      window.addEventListener('load', () => {
        navigator.serviceWorker.register('/sw.js')
          .then((registration) => {
            console.log('Service Worker registered successfully:', registration);
          })
          .catch((registrationError) => {
            console.log('Service Worker registration failed:', registrationError);
          });
      });
    }
  }, []);

  return null;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
          <ServiceWorkerRegistration />
          {children}
        </Provider>
      </body>
    </html>
  );
}
